spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/securevault
spring.datasource.username=postgres
spring.datasource.password=kowsi

spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ==========================================
# EMAIL CONFIGURATION
# ==========================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kowsika259@gmail.com
spring.mail.password=llqr fivi tjth srga

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true