spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/securevault
spring.datasource.username=postgres
spring.datasource.password=kowsi

spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect